### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aolko**
Added better alternative telegram groups

### CODE REVIEW

**Review by ringabout — COMMENTED** [review]
No, thanks. The list only includes chats with enough people.

**Comment by aolko** [comment]
> No, thanks. The list only includes chats with enough people.

Discrimination is verily frowned upon, you know.

**Comment by PhilippMDoerner** [comment]
An unknown with no established reputation and trust with the existing community other than to say "nim might be great, but it lacks sugar and community is goddamn terrible", wants to add an unknown community to a list of communities provided by one of nim's currently main contributors.

This is an entirely understandable decision.

**Comment by aolko** [comment]
> An unknown with no established reputation and trust with the existing community other than going on the discord servers to say "nim might be great, but it lacks sugar and community is goddamn terrible", wants to add an unknown group to ringabout's list, who is currently one of nim-langs major contributors.
> 
> This is an entirely understandable decision.

might as well redo my fork as my own list, while you keep stroking your "established reputation" and "trust"

**Pull request closed without merging**
